### ISSUE TITLE
Error on building

### ISSUE THREAD

**Issue by TimNZ** [develar/onshape-desktop-shell#33]
OS X 10.12.4

1. git clone ..
2. npm install
3. npm run dist

Error:

```
➜  onshape-desktop-shell git:(master) ✗ npm run dist

> Onshape@0.5.8 dist /Users/timshnaider/Desktop/Development/electron/onshape-desktop-shell
> yarn compile && build

yarn compile v0.16.1
$ rimraf app/out && tsc 
✨  Done in 1.46s.
Rebuilding native production dependencies for darwin:x64
Packaging for darwin x64 using electron 1.6.3 to dist/mac
⚠️  App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
Building macOS zip
Building DMG
Error: Exit code: 255. Command failed: /usr/bin/perl /var/folders/tk/_gk0g0x95c15zp68pqz04f280000gn/T/electron-builder-DVJzQ7/0-2-dmgProperties.pl
Error: Error querying file
Cannot query image dimensions at /var/folders/tk/_gk0g0x95c15zp68pqz04f280000gn/T/electron-builder-DVJzQ7/0-2-dmgProperties.pl line 22.

Error: Error querying file
Cannot query image dimensions at /var/folders/tk/_gk0g0x95c15zp68pqz04f280000gn/T/electron-builder-DVJzQ7/0-2-dmgProperties.pl line 22.

    at /Users/timshnaider/Desktop/Development/electron/onshape-desktop-shell/node_modules/electron-builder-util/src/util.ts:75:16
    at ChildProcess.exithandler (child_process.js:209:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at exec (/Users/timshnaider/Desktop/Development/electron/onshape-desktop-shell/node_modules
```

**Comment by develar** [comment]
Please use git-lfs to clone this repo. Please use `git lfs pull` to download required files.
